// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.StarsLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("starName")]
        public string StarName { get; set; }

        [JsonProperty("mass")]
        public double? Mass { get; set; }

        [JsonProperty("diameter")]
        public long? Diameter { get; set; }

        [JsonProperty("galX")]
        public double? GalX { get; set; }

        [JsonProperty("galY")]
        public double? GalY { get; set; }

        [JsonProperty("galZ")]
        public double? GalZ { get; set; }

        [JsonProperty("dist")]
        public double? Dist { get; set; }

        [JsonProperty("starType")]
        public string StarType { get; set; }

        [JsonProperty("temp")]
        public long? Temp { get; set; }

        [JsonProperty("color")]
        public string Color { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
